"common":
  model: TCN
  des: test
  loss: MSE
  use_amp: false
  dropout: 0.3  # range: [0.1, 0.9]
  d_model: 48 # [32, 64, 96, 128]
  e_layers: 4 # [1, 2, 3, 4, 5]
  kernel_size: 3 # [3, 5, 7, 9, 11]
  learning_rate: 0.004 # range: [5e-5, 1e-3]
  batch_size: 32 # 一般取2，4，8的倍数
  train_epochs: 10
  patience: 10
  lradj: type1

"96":
  batch_size: 16
  e_layers: 4
  d_model: 48
  dropout: 0.3
  learning_rate: 0.001
  kernel_size: 3

"192":
  batch_size: 32
  d_layers: 2
  d_model: 96
  dropout: 0.6249664909676028
  kernel_size: 3
  learning_rate: 0.000808330518804057

"336":
  batch_size: 48
  d_layers: 1
  d_model: 64
  dropout: 0.5360072669967711
  e_layers: 1
  kernel_size: 7
  learning_rate: 0.00045800037531870625

"720":
  batch_size: 16
  d_layers: 2
  d_model: 32
  dropout: 0.5656949759590233
  e_layers: 3
  kernel_size: 5
  learning_rate: 0.0009426369671262148