
"common":
  model: TimeFilter
  des: test
  loss: MSE
  use_amp: false
  dropout: 0.8
  d_model: 96
  d_ff: 96
  e_layers: 2
  d_layers: 1
  patch_len: 2
  use_norm: 0
  top_p: 0.0
  factor: 3
  pos: 0
  learning_rate: 0.0001
  batch_size: 32
  train_epochs: 10
  patience: 10
  lradj: type1

"96":
  batch_size: 32
  d_ff: 64
  d_layers: 2
  d_model: 128
  dropout: 0.5506872607498472
  e_layers: 3
  learning_rate: 6.232145354454002e-05
  patch_len: 2

"192":
  batch_size: 24
  d_ff: 64
  d_layers: 2
  d_model: 32
  dropout: 0.6146400031849316
  e_layers: 3
  learning_rate: 5.958120106288615e-05
  patch_len: 16
  train_epochs: 10
  patience: 10

"336":
  batch_size: 24
  d_ff: 64
  d_layers: 2
  d_model: 32
  dropout: 0.6146400031849316
  e_layers: 3
  learning_rate: 5.958120106288615e-05
  patch_len: 16
  train_epochs: 10
  patience: 10

"720":
  batch_size: 16
  d_ff: 64
  d_layers: 1
  d_model: 96
  dropout: 0.7413887721356673
  e_layers: 3
  learning_rate: 0.0009539842181971406
  patch_len: 4
  train_epochs: 10
  patience: 5