# ----- model define -----
expand: 2
d_conv: 4
top_k: 5
num_kernels: 6
n_heads: 8
d_layers: 1
d_ff: 2048
moving_avg: 25
factor: 1
distil: true  # 对应原来 default=True（action='store_false'）
dropout: 0.1
embed: timeF
activation: gelu
channel_independence: 1
decomp_method: moving_avg
use_norm: 1
down_sampling_layers: 0
down_sampling_window: 1
down_sampling_method: null
seg_len: 96
# de-stationary projector params
p_hidden_dims: [128, 128]
p_hidden_layers: 2

# predict_len=[48]
d_model: 48 
e_layers: 4 

# predict_len=[24]

# optimization
learning_rate: 0.005
des: test
loss: MSE
lradj: type1
use_amp: false        # 对应 action='store_true'

# TimeXer
patch_len: 16

# GCN
node_dim: 10
gcn_depth: 2
gcn_dropout: 0.3
propalpha: 0.3
conv_channel: 32
skip_channel: 32
individual: false      # 对应 action='store_true'

# TimeFilter
alpha: 0.1
top_p: 0.5
pos: 1
