"common":
  model: TimeFilter
  des: test
  loss: MSE
  use_amp: false
  dropout: 0.1
  d_model: 512
  d_ff: 1024
  e_layers: 2
  d_layers: 1
  patch_len: 48
  use_norm: 1
  top_p: 0.0
  factor: 3
  pos: 0
  learning_rate: 0.0001
  batch_size: 32
  train_epochs: 10
  patience: 10
  lradj: type1

"12":
  batch_size: 16
  d_layers: 1
  d_model: 512
  d_ff: 512
  dropout: 0.2
  e_layers: 2
  learning_rate: 0.001
  patch_len: 48
  train_epochs: 20
  patience: 10

"24":
  batch_size: 16
  d_layers: 1
  d_model: 512
  d_ff: 512
  dropout: 0.2
  e_layers: 2
  learning_rate: 0.001
  patch_len: 48
  train_epochs: 20
  patience: 10

"48":
  batch_size: 16
  d_layers: 1
  d_model: 512
  d_ff: 512
  dropout: 0.2
  e_layers: 2
  learning_rate: 0.001
  patch_len: 48
  train_epochs: 20
  patience: 10