ETTh1:
  data_type: ETTh1
  root_path: dataset/ETT-small/
  data_path: ETTh1.csv

ETTh2:
  data_type: ETTh2
  root_path: dataset/ETT-small/
  data_path: ETTh2.csv

ETTm1:
  data_type: ETTm1
  root_path: dataset/ETT-small/
  data_path: ETTm1.csv

ETTm2:
  data_type: ETTm2
  root_path: dataset/ETT-small/
  data_path: ETTm2.csv

Exchange:
  data_type: custom
  root_path: dataset/exchange_rate/
  data_path: exchange_rate.csv

Illness:
  data_type: custom
  root_path: dataset/illness/
  data_path: national_illness.csv

Weather:
  data_type: custom
  root_path: dataset/weather/
  data_path: weather.csv

Traffic:
  data_type: custom
  root_path: dataset/traffic/
  data_path: traffic.csv

Electricity:
  data_type: custom
  root_path: dataset/electricity/
  data_path: electricity.csv

PEMS03:
  data_type: PEMS
  root_path: dataset/PEMS/
  data_path: PEMS03.npz
  Target: 141

PEMS04:
  data_type: PEMS
  root_path: dataset/PEMS/
  data_path: PEMS04.npz
  Target: 97

PEMS07:
  data_type: PEMS
  root_path: dataset/PEMS/
  data_path: PEMS07.npz
  Target: 178

PEMS08:
  data_type: PEMS
  root_path: dataset/PEMS/
  data_path: PEMS08.npz
  Target: 9
  
# M4:
#   data_type: m4
#   root_path: dataset/m4/
#   seasonal_patterns: ['Monthly', 'Yearly', 'Quarterly', 'Weekly', 'Daily', 'Hourly']