"common":
  seq_len: 96
  embed_size: 16
  d_model: 512
  d_ff: 512
  batch_size: 32
  learning_rate: 0.0005
  itr: 1
  e_layers: 3
  lossfun_alpha: 0.5
  test_batch_size: 16
  test_mode: 0
  CKA_flag: 0
  fix_seed: 1
  resume_training: 0
  resume_epoch: 0
  save_every_epoch: 0
  use_revin: 1
  use_norm: 1
  send_mail: 0
  save_pdf: 0
  patience: 10
  lradj: cosine
  loss_mode: L1
  train_ratio: 1.0
  dropout: 0.0
  plot_mat_flag: 0
  plot_mat_label: ECL_attn011
  attn_enhance: 1
  attn_softmax_flag: 0
  attn_weight_plus: 1
  attn_outside_softmax: 1

"96":
  embed_size: 16
  d_model: 512
  d_ff: 512
  learning_rate: 0.0005
  dropout: 0.0
  train_epochs: 30

"192":
  embed_size: 16
  d_model: 512
  d_ff: 512
  learning_rate: 0.0005
  dropout: 0.0
  train_epochs: 50

"336":
  embed_size: 16
  d_model: 512
  d_ff: 512
  learning_rate: 0.0005
  dropout: 0.0
  train_epochs: 50

"720":
  embed_size: 16
  d_model: 512
  d_ff: 512
  learning_rate: 0.0005
  dropout: 0.0
  train_epochs: 50
